### ISSUE TITLE
Clicking "Choose Tags" in Asset Warehouse causes crash

### ISSUE THREAD

**Issue by valentinegb** [StressLevelZero/MarrowSDK#27]
Clicking the **Choose Tags** button in the Asset Warehouse causes Unity to crash.

## Images
![Screenshot 2022-09-30 at 8 30 58 PM](https://user-images.githubusercontent.com/35977727/193386011-c16b0359-a693-4c70-9b87-6699653620c9.png)

## Crash Message
```
Obtained 89 stack frames.
#0  0x000001aa95b204 in __pthread_kill
#1  0xbe0f0001aa8cb2c8 in abort
#2  0xd438001aa94bb18 in __cxxabiv1::__aligned_malloc_with_fallback(unsigned long)
#3  0xc06f0001aa93ba0c in demangling_unexpected_handler()
#4  0x2c798001aa63f764 in _objc_terminate()
#5  0x795a8001aa94aeb4 in std::__terminate(void (*)())
#6  0xf4058001aa94dc2c in __cxa_get_exception_ptr
#7  0x5f4b0001aa94dbd8 in __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
#8  0x20d8001aa637008 in objc_exception_throw
#9  0xd26d0001aba2bc50 in -[NSCalendarDate initWithCoder:]
#10 0xb1790001adcd9334 in -[NSView initWithFrame:]
#11 0x24580001ade8d934 in -[NSNextStepFrame initWithFrame:styleMask:owner:]
#12 0x406d8001adcd71b4 in -[NSWindow _commonInitFrame:styleMask:backing:defer:]
#13 0x88030001adcd6c0c in -[NSWindow _initContent:styleMask:backing:defer:contentView:]
#14 0x85240001ade32158 in -[NSPanel _initContent:styleMask:backing:defer:contentView:]
#15 0x74038001adcd6954 in -[NSWindow initWithContentRect:styleMask:backing:defer:]
#16 0xda2f0001ade3210c in -[NSPanel initWithContentRect:styleMask:backing:defer:]
#17 0xb213000106cd8724 in -[OTNoTitlePanel initWithContentRect:styleMask:backing:defer:]
#18 0x00000106cd8e7c in ContainerWindow::Init(MonoBehaviour*, RectT<float>, int, Vector2f const&, Vector2f const&)
#19 0x00000105aef288 in ContainerWindowBindings::Internal_Show(MonoBehaviour*, RectT<float> const&, int, Vector2f const&, Vector2f const&)
#20 0x00000104819fb8 in ContainerWindow_CUSTOM_Internal_Show_Injected(ScriptingBackendNativeObjectPtrOpaque*, RectT<float> const&, int, Vector2f const&, Vector2f const&)
#21 0x00000305048bc0 in  (wrapper managed-to-native) UnityEditor.ContainerWindow:Internal_Show_Injected (UnityEditor.ContainerWindow,UnityEngine.Rect&,int,UnityEngine.Vector2&,UnityEngine.Vector2&) [{0x2a33db220} + 0x90]  (0x305048b30 0x305048c30) [0x137d82a80 - Unity Child Domain]
#22 0x00000305048ad0 in  UnityEditor.ContainerWindow:Internal_Show (UnityEngine.Rect,int,UnityEngine.Vector2,UnityEngine.Vector2) [{0x2c72f8ec8} + 0x48]  (0x305048a88 0x305048adc) [0x137d82a80 - Unity Child Domain]
#23 0x000003051cbdf0 in  UnityEditor.ContainerWindow:ShowPopupWithMode (UnityEditor.ShowMode,bool) [{0x2c73d1e88} + 0xa8] [/Users/bokken/buildslave/unity/build/Editor/Mono/ContainerWindow.cs :: 117u] (0x3051cbd48 0x3051cc010) [0x137d82a80 - Unity Child Domain]
#24 0x000003051d34f8 in  UnityEditor.EditorWindow:ShowPopupWithMode (UnityEditor.ShowMode,bool) [{0x2c74312b8} + 0x298] [/Users/bokken/buildslave/unity/build/Editor/Mono/EditorWindow.cs :: 565u] (0x3051d3260 0x3051d350c) [0x137d82a80 - Unity Child Domain]
#25 0x000003051d2c3c in  UnityEditor.EditorWindow:ShowAsDropDown (UnityEngine.Rect,UnityEngine.Vector2,UnityEditor.PopupLocation[],UnityEditor.ShowMode,bool) [{0x2c7431380} + 0xcc] [/Users/bokken/buildslave/unity/build/Editor/Mono/EditorWindow.cs :: 621u] (0x3051d2b70 0x3051d2ea8) [0x137d82a80 - Unity Child Domain]
#26 0x000003051d26d4 in  UnityEditor.PopupWindow:Init (UnityEngine.Rect,UnityEditor.PopupWindowContent,UnityEditor.PopupLocation[],UnityEditor.ShowMode,bool) [{0x2c70d5668} + 0x174] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/PopupWindow.cs :: 103u] (0x3051d2560 0x3051d26e8) [0x137d82a80 - Unity Child Domain]
#27 0x000003051d20dc in  UnityEditor.PopupWindow:Show (UnityEngine.Rect,UnityEditor.PopupWindowContent,UnityEditor.PopupLocation[],UnityEditor.ShowMode) [{0x2c70d5618} + 0x1c4] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/PopupWindow.cs :: 72u] (0x3051d1f18 0x3051d211c) [0x137d82a80 - Unity Child Domain]
#28 0x000003051d1eb8 in  UnityEditor.PopupWindow:Show (UnityEngine.Rect,UnityEditor.PopupWindowContent,UnityEditor.PopupLocation[]) [{0x2c70d55f0} + 0x40] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/PopupWindow.cs :: 44u] (0x3051d1e78 0x3051d1ec4) [0x137d82a80 - Unity Child Domain]
#29 0x000003051d1e58 in  UnityEditor.PopupWindow:Show (UnityEngine.Rect,UnityEditor.PopupWindowContent) [{0x2c70d55c8} + 0x38] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/PopupWindow.cs :: 39u] (0x3051d1e20 0x3051d1e64) [0x137d82a80 - Unity Child Domain]
#30 0x0000030519faf4 in  SLZ.MarrowEditor.AssetWarehouseWindow:OnGUI () [{0x2a02f90f8} + 0x1534] [/Users/valentinebriese/Documents/Unity Projects/BONELAB Test Mod/Library/PackageCache/com.stresslevelzero.marrow.sdk@cf57525691/SLZ.Marrow.SDK.Editor/SLZ.MarrowEditor/AssetWarehouseWindow.cs :: 286u] (0x30519e5c0 0x30519fe8c) [0x137d82a80 - Unity Child Domain]
#31 0x0000030380b24c in  UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect) [{0x2c73c5988} + 0x10c] [/Users/bokken/buildslave/unity/build/Editor/Mono/HostView.cs :: 449u] (0x30380b140 0x30380b464) [0x137d82a80 - Unity Child Domain]
#32 0x0000030380b088 in  UnityEditor.DockArea:DrawView (UnityEngine.Rect) [{0x2c73c4c08} + 0x38] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs :: 388u] (0x30380b050 0x30380b0a0) [0x137d82a80 - Unity Child Domain]
#33 0x000003037fb184 in  UnityEditor.DockArea:OldOnGUI () [{0x2c73c4be0} + 0x614] [/Users/bokken/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs :: 380u] (0x3037fab70 0x3037fb1e0) [0x137d82a80 - Unity Child Domain]
#34 0x000003037d4fdc in  UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool) [{0x2c76dcee0} + 0x5a4] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 352u] (0x3037d4a38 0x3037d5a70) [0x137d82a80 - Unity Child Domain]
#35 0x000003037d42e0 in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool) [{0x2c76dd0c0} + 0x2e0] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 695u] (0x3037d4000 0x3037d4428) [0x137d82a80 - Unity Child Domain]
#36 0x00000303943774 in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool) [{0x2c76dd098} + 0xe4] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 665u] (0x303943690 0x303943794) [0x137d82a80 - Unity Child Domain]
#37 0x00000303943628 in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool) [{0x2c76dd070} + 0x30] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 658u] (0x3039435f8 0x30394363c) [0x137d82a80 - Unity Child Domain]
#38 0x00000303fe4ee8 in  UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool) [{0x2c76dcf80} + 0x90] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 618u] (0x303fe4e58 0x303fe4f3c) [0x137d82a80 - Unity Child Domain]
#39 0x00000303fe4c78 in  UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool) [{0x2c76dcf58} + 0x468] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 607u] (0x303fe4810 0x303fe4c98) [0x137d82a80 - Unity Child Domain]
#40 0x00000302c5b2b4 in  UnityEngine.UIElements.IMGUIContainer:HandleEvent (UnityEngine.UIElements.EventBase) [{0x2eec2baf0} + 0xec] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 535u] (0x302c5b1c8 0x302c5b2ec) [0x137d82a80 - Unity Child Domain]
#41 0x00000302c32c7c in  UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase) [{0x17fd37190} + 0x54] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/EventHandler.cs :: 152u] (0x302c32c28 0x302c32cac) [0x137d82a80 - Unity Child Domain]
#42 0x00000303fe20c8 in  UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x2f4c702e0} + 0x528] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/MouseCaptureDispatchingStrategy.cs :: 92u] (0x303fe1ba0 0x303fe22f4) [0x137d82a80 - Unity Child Domain]
#43 0x00000302c30c28 in  UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool) [{0x17fd36e80} + 0xb8] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 383u] (0x302c30b70 0x302c30d88) [0x137d82a80 - Unity Child Domain]
#44 0x00000302c30664 in  UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x17fd36490} + 0x134] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 347u] (0x302c30530 0x302c30834) [0x137d82a80 - Unity Child Domain]
#45 0x00000302c377f8 in  UnityEngine.UIElements.EventDispatcher:ProcessEventQueue () [{0x29fe95658} + 0xe0] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 307u] (0x302c37718 0x302c37930) [0x137d82a80 - Unity Child Domain]
#46 0x00000302c35b30 in  UnityEngine.UIElements.EventDispatcher:OpenGate () [{0x2f4dfbc30} + 0x60] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 272u] (0x302c35ad0 0x302c35b40) [0x137d82a80 - Unity Child Domain]
#47 0x00000302c35a70 in  UnityEngine.UIElements.EventDispatcherGate:Dispose () [{0x2f4dfbb48} + 0x20] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 76u] (0x302c35a50 0x302c35a80) [0x137d82a80 - Unity Child Domain]
#48 0x00000302c30810 in  UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x17fd36490} + 0x2e0] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 372u] (0x302c30530 0x302c30834) [0x137d82a80 - Unity Child Domain]
#49 0x00000302c2ff84 in  UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode) [{0x17fd36380} + 0xf4] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 223u] (0x302c2fe90 0x302c2ffec) [0x137d82a80 - Unity Child Domain]
#50 0x00000302c2fe20 in  UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode) [{0x2f4dfce68} + 0x68] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Panel.cs :: 420u] (0x302c2fdb8 0x302c2fe30) [0x137d82a80 - Unity Child Domain]
#51 0x00000303780b78 in  UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel) [{0x2c9cfcab8} + 0x300] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 468u] (0x303780878 0x303780c94) [0x137d82a80 - Unity Child Domain]
#52 0x00000303780630 in  UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&) [{0x2c370f340} + 0xc8] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 211u] (0x303780568 0x303780660) [0x137d82a80 - Unity Child Domain]
#53 0x00000303780474 in  UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr) [{0x2c9cfca38} + 0x94] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 74u] (0x3037803e0 0x303780508) [0x137d82a80 - Unity Child Domain]
#54 0x00000303780380 in  UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr) [{0x29f89fd90} + 0x20] [/Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 28u] (0x303780360 0x303780390) [0x137d82a80 - Unity Child Domain]
#55 0x000003037801e4 in  UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) [{0x15259dca0} + 0x64] [/Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs :: 189u] (0x303780180 0x3037801fc) [0x137d82a80 - Unity Child Domain]
#56 0x00000303780280 in  (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr_intptr& (object,intptr,intptr,intptr) [{0x2c9db2100} + 0x80]  (0x303780200 0x303780320) [0x137d82a80 - Unity Child Domain]
#57 0x0000016649590c in mono_jit_runtime_invoke
#58 0x0000016661b6a8 in do_runtime_invoke
#59 0x0000016661b5c8 in mono_runtime_invoke
#60 0x000001050bba48 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#61 0x000001050b6bb8 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
#62 0x0000010519c3c4 in Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent(int, void*, bool*, ScriptingExceptionPtr*)
#63 0x00000105b269b0 in GUIView::ProcessRetainedMode(InputEvent&, GUIState&, int)
#64 0x00000106ce34b4 in GUIView::OnInputEvent(InputEvent&)
#65 0x00000105b25bec in GUIView::ProcessInputEvent(InputEvent&)
#66 0x00000106cf1b60 in -[GUIRenderView handleEvent:]
#67 0x00000106cf2248 in -[GUIRenderView mouseUp:]
#68 0x000001addf3950 in -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]
#69 0x73588001addf2f50 in -[NSWindow(NSEventRouting) sendEvent:]
#70 0x7e4a0001addf217c in -[NSApplication(NSEvent) sendEvent:]
#71 0xf134800106cddcb4 in -[EditorApplicationPrincipalClass sendEvent:]
#72 0x00000106ce1078 in -[EditorApplication TickTimer]
#73 0x000001ab9af86c in __NSFireTimer
#74 0xf02a8001aaa8b5b8 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
#75 0x35140001aaa8b260 in __CFRunLoopDoTimer
#76 0x676b8001aaa8adb8 in __CFRunLoopDoTimers
#77 0xbc0d0001aaa707a0 in __CFRunLoopRun
#78 0xe81b0001aaa6f8e4 in CFRunLoopRunSpecific
#79 0x50318001b40de2e4 in RunCurrentEventLoopInMode
#80 0xb31f8001b40ddf74 in ReceiveNextEventCommon
#81 0x1d670001b40dde70 in _BlockUntilNextEventMatchingListInModeWithFilter
#82 0x9d2d0001adcc5b94 in _DPSNextEvent
#83 0xf3740001adcc4d24 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
#84 0x732d8001adcb9154 in -[NSApplication run]
#85 0x1d198001adc906c4 in NSApplicationMain
#86 0x1f0b000106cde3c8 in EditorMain(int, char const**)
#87 0x00000106cde700 in main
#88 0x000001aa667e50 in start
```

## Crash Logs
[DownloadAssistant.log](https://github.com/StressLevelZero/MarrowSDK/files/9689446/DownloadAssistant.log)
[Editor-prev.log](https://github.com/StressLevelZero/MarrowSDK/files/9689447/Editor-prev.log)
[Editor.log](https://github.com/StressLevelZero/MarrowSDK/files/9689449/Editor.log)
[MonoDevelop.log](https://github.com/StressLevelZero/MarrowSDK/files/9689452/MonoDevelop.log)
[Player.log](https://github.com/StressLevelZero/MarrowSDK/files/9689453/Player.log)
[Unity.Entitlements.Audit.log](https://github.com/StressLevelZero/MarrowSDK/files/9689468/Unity.Entitlements.Audit.log)
[Unity.Licensing.Client.log](https://github.com/StressLevelZero/MarrowSDK/files/9689470/Unity.Licensing.Client.log)
[upm.log](https://github.com/StressLevelZero/MarrowSDK/files/9689473/upm.log)

**Comment by valentinegb** [comment]
Oh, I'll try this again on Unity 2021.3.11f1, I'm testing the SDK with another mod on that version and so far the UI in Unity has been less janky than 2021.3.5f1, so maybe it'll work in that version?

**Comment by valentinegb** [comment]
Nope, it still crashes, never mind haha-
